#!/usr/bin/env bash

WatchPulse()
{
	WatchIgnore=($(cat ./.watchignore))
	inotifywait -mr --timefmt '%d/%m/%y %H:%M' --format '%T %w %f' \
	-e close_write . | while read date time dir file; do
		updateFile=${file}
		WatchCompare=(${WatchIgnore[@]##"$updateFile"})
		if [ ${#WatchCompare[@]} -ne ${#WatchIgnore[@]} ];then
			#echo skipping $updateFile
			continue
		fi
		#convert absolute path to relative
		#updateFileREL=`echo "$FILECHANGE" | sed 's_'$curPath'/__'`
        pkill inotify
        jsdoc -r . -d site
        echo -e "\033[0;36msite updated $time\033[0;m"
        ./watchdoc
        rm -rf ~/ftpimp/site
	done
}

WatchPulse

